version: '3.8'

services:
  # --- C-UNIT WEB SERVICE (НАШЕ API) ---
  c-unit-gateway:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - BTCPAY_HOST=http://btcpay:49392 # Внутренний адрес Docker
      - BTCPAY_API_KEY=${BTCPAY_API_KEY}
      - BTCPAY_STORE_ID=${BTCPAY_STORE_ID}
    depends_on:
      - qdrant
      - btcpay
    volumes:
      - .:/app

  # --- ПАМЯТЬ (ВЕКТОРНАЯ БАЗА ДАННЫХ) ---
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  # --- ПЛАТЕЖНЫЙ ШЛЮЗ (КРИПТО) ---
  btcpay:
    image: btcpayserver/btcpayserver:latest
    ports:
      - "8080:80"  # Доступ к BTCPay UI
      - "49392:49392"
    environment:
      - BTCPAY_ROOTPATH=/
      - BTCPAY_NETWORK=mainnet # или regtest для теста
      - BTCPAY_BIND=0.0.0.0:80
      - BTCPAY_HTTPS=false # Render/Cloudflare обеспечат HTTPS
    volumes:
      - btcpay_data:/data

volumes:
  qdrant_storage:
  btcpay_data:

