---
services:
  - type: web
    name: sodmaster-c-unit
    runtime: python
    pythonVersion: "3.12"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    envVars:
      - key: OPENROUTER_API_KEY
        fromService:
          type: envVarGroup
          name: sodmaster-keys
      - key: LEONARDO_API_KEY
        fromService:
          type: envVarGroup
          name: sodmaster-keys
      - key: OPENAI_API_KEY
        fromService:
          type: envVarGroup
          name: sodmaster-keys
      - key: ANTHROPIC_API_KEY
        fromService:
          type: envVarGroup
          name: sodmaster-keys
      - key: EXA_API_KEY
        fromService:
          type: envVarGroup
          name: sodmaster-keys
      - key: SERPER_API_KEY
        fromService:
          type: envVarGroup
          name: sodmaster-keys
      - key: BTCPAY_HOST
        value: "btcpay_placeholder"
      - key: BTCPAY_STORE_ID
        value: "store_id_placeholder"
      - key: BTCPAY_API_KEY
        value: "api_key_placeholder"
      - key: QDRANT_HOST
        value: "qdrant_placeholder"

---
